---

image:
  pullPolicy: Always
  repository: ghcr.io/salt-labs/arweave-miner
  tag: "2.5.1.0"

updateStrategy: Recreate

appVolumeMounts:
  data:

    emptyDir: true
    mountPath: /data

    hostPathEnabled: false

arweaveRewardAddress: "0000000000000000000000000"

arweaveHostPort: 1984

logLevel: "DEBUG"

arweaveSyncEnabled: "false"

arweaveMineJobs: 5
arweaveSyncMineJobs: 25
arweaveSyncJobs: 100

arweavePeersNum: 50

resources:
  requests:
    cpu: "2"
    memory: "8Gi"
  limits:
    cpu: "8"
    memory: "32Gi"
