
image:
  pullPolicy: Always
  repository: ghcr.io/salt-labs/arweave-miner
  tag: "2.5.0.0"

updateStrategy: Recreate

arweaveRewardAddress: "0000000000000000000000000"

appVolumeMounts:
  data:
    emptyDir: true
    mountPath: /data
