
image:
  pullPolicy: Always
  repository: ghcr.io/salt-labs/arweave-miner
  tag: "2.5.0.0"

updateStrategy: Recreate

# TODO: Add to questions.yaml
resources:
  limits:
    cpu: "8"
    memory: "32Gi"
  requests:
    cpu: "2"
    memory: "8Gi"
