---

apiVersion: kappctrl.k14s.io/v1alpha1
kind: App

metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
  annotations:
    kapp.k14s.io/change-rule.create-order: "upsert after upserting crd"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting crd"

spec:
  paused: {{ .Values.kapp.paused | default "false" }}
  canceled: {{ .Values.kapp.canceled | default "false" }}
  noopDelete: {{ .Values.kapp.noopDelete | default "false" }}
  syncPeriod: 1m
  {{- if .Values.kapp.cluster }}
  cluster:
    namespace: {{ .Values.kapp.cluster.namespace }}
    kubeconfigSecretRef:
      name: {{ .Values.kapp.cluster.kubeconfigSecretRef.name }}
      key: {{ .Values.kapp.cluster.kubeconfigSecretRef.key }}
  {{ else }}
  serviceAccountName: {{ .Values.namespace }}-sa
  {{- end}}

  # TODO: https://carvel.dev/kapp-controller/docs/v0.32.0/app-spec/
  fetch:
  {{- if .Values.git.enabled }}
    - git:
      url: {{ .Values.git.repo }}
      ref: {{ .Values.git.branch }}
      subPath: {{ .Values.git.path }}
    {{- if .Values.secrets.enabled }}
      secretRef:
        name: {{ .Values.secrets.secretRef.name }}
        namespace: {{ .Values.secrets.secretRef.namespace }}
    {{- end }}
  {{- end }}

  {{- if .Values.imgpkg.enabled }}
    - imgpkgBundle:
  {{- end -}}

  {{- if .Values.helm.enabled }}
    - helm:
  {{- end }}

  template:
    - ytt: {}

  deploy:
    - kapp: {}
