---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-app-cr
rules:
- apiGroups:
	- ""
  resources:
  	- "configmaps"
  verbs:
    - "get"
	- "list"
	- "create"
	- "update"
	- "delete"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace }}-app-cr
subjects:
  - kind: ServiceAccount
	name: {{ .Values.namespace }}-sa
	namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.namespace }}-app-cr
  apiGroup: rbac.authorization.k8s.io
