apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    site: {{ .Release.Name }}
  annotations:
    ix.upgrade.scale.down.workload: "true"
spec:
  strategy:
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      site: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
        site: {{ .Release.Name }}
      annotations:
        ix.upgrade.scale.down.workload: "true"
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: {{ .Chart.Name }}
              protocol: TCP
              containerPort: 1984
              hostPort: 1984
          readinessProbe:
            tcpSocket:
              port: {{ .Chart.Name }}
            initialDelaySeconds: 5
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: {{ .Chart.Name }}
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          env:
            - name: ARWEAVE_REWARD_ADDRESS
              value: {{ required "Reward address not set" .Values.arweaveRewardAddress }}
          volumeMounts:
            - name: data
              mountPath: {{ required "mountPath not set" .Values.appVolumeMounts.data.mountPath }}
      volumes:
        - name: data
          {{ if .Values.appVolumeMounts.data.emptyDir }}
          emptyDir: {}
          {{ else if .Values.appVolumeMounts.data.hostPathEnabled }}
          hostPath:
            path: {{ .Values.appVolumeMounts.data.hostPath }}
          {{ else if .Values.appVolumeMounts.data.datasetName }}
            path: {{ .Values.appVolumeMounts.data.datasetName }}
          {{ end }}
